sudo: required

services:
 - docker

language: scala

scala:
 - 2.11.7

jdk:
 - oraclejdk8

script:
 - sbt test package

after_success:
 - if [[ "$TRAVIS_BRANCH" == release* ]]; then
     docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD";
     sbt docker:publish;
   fi
